### ISSUE TITLE
Google login error

### ISSUE THREAD

**Issue by jeblond** [MonsterMMORPG/Pokemon-Go-Bot#8]
Cannot login google account:

[10:52:25](INFO) Logging in via: Google
[10:52:26](ERROR) Please visit  and enter

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Forms.Clipboard.SetText(String text)
   at PokemonGo.RocketAPI.Login.GoogleLogin.<>c__DisplayClass6_0.<GetDeviceCode>b__0() in E:\ultimatebot\Pokemon-Go-Bot\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 65
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
^C

**Comment by janhenrlk** [comment]
He need to fix it for us :/
